version: '3.8'

services:
  sneaker:
    image: ghcr.io/vcsg8/sneaker:latest
    container_name: sneaker-server
    restart: unless-stopped
    ports:
      - "7788:7788"
    volumes:
      - /app/config.json:/config/config.json:ro
    environment:
      - TZ=UTC
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7788/api/servers"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 