name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npx webpack build

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.17

      - name: Build Go binary
        run: go build -o sneaker ./cmd/sneaker-server/main.go

      - name: Extract version from package.json
        id: pkg
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/vcsg8/sneaker:${{ steps.pkg.outputs.version }} -t ghcr.io/vcsg8/sneaker:latest .

      - name: Push Docker image (version)
        run: docker push ghcr.io/vcsg8/sneaker:${{ steps.pkg.outputs.version }}

      - name: Push Docker image (latest)
        run: docker push ghcr.io/vcsg8/sneaker:latest

      - name: Save Docker image as artifact
        run: docker save ghcr.io/vcsg8/sneaker:${{ steps.pkg.outputs.version }} | gzip > sneaker-image.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: sneaker-docker-image
          path: sneaker-image.tar.gz 